language: ruby
rvm:
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
before_install:
  - gem update --system
  - gem --version
script: bundle exec rake test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f8a813b3063636aa18f1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false